server:
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: ebs-csi-sc

  service:
    type: ClusterIP

alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: ebs-csi-sc
